# Generated by Django 2.2 on 2019-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
